export const restaurantCategoriesEs = [
	{ label: "Italiana", value: "italian" },
	{ label: "Mexicana", value: "mexican" },
	{ label: "Japonesa", value: "japanese" },
	{ label: "Parrilla Argentina", value: "argentinian-grill" },
	{ label: "China", value: "chinese" },
	{ label: "Tailandesa", value: "thai" },
	{ label: "India", value: "indian" },
	{ label: "Francesa", value: "french" },
	{ label: "Española", value: "spanish" },
	{ label: "Mediterránea", value: "mediterranean" },
	{ label: "Vegetariana", value: "vegetarian" },
	{ label: "Vegana", value: "vegan" },
	{ label: "Comida Rápida", value: "fast-food" },
	{ label: "Mariscos", value: "seafood" },
	{ label: "Sushi", value: "sushi" },
	{ label: "Griega", value: "greek" },
	{ label: "Coreana", value: "korean" },
	{ label: "Brasileña", value: "brazilian" },
	{ label: "Peruana", value: "peruvian" },
	{ label: "Árabe", value: "arabic" },
	{ label: "Vietnamita", value: "vietnamese" },
	{ label: "Fusión", value: "fusion" },
	{ label: "Gourmet", value: "gourmet" },
	{ label: "De la Granja a la Mesa", value: "farm-to-table" },
	{ label: "Buffet", value: "buffet" },
	{ label: "Hamburguesas", value: "burgers" },
	{ label: "Pizza", value: "pizza" },
	{ label: "Sándwiches", value: "sandwiches" },
	{ label: "Tex-Mex", value: "tex-mex" },
	{ label: "Barbacoa", value: "barbecue" },
	{ label: "Cajún", value: "cajun" },
	{ label: "Caribeña", value: "caribbean" },
	{ label: "Escandinava", value: "scandinavian" },
	{ label: "Polaca", value: "polish" },
	{ label: "Turca", value: "turkish" },
	{ label: "Mongola", value: "mongolian" },
	{ label: "Filipina", value: "filipino" },
	{ label: "Hawaiana", value: "hawaiian" },
	{ label: "Sudafricana", value: "south-african" },
	{ label: "Etíope", value: "ethiopian" },
	{ label: "Persa", value: "persian" },
	{ label: "Armenia", value: "armenian" },
	{ label: "Ucraniana", value: "ukrainian" },
	{ label: "Sueca", value: "swedish" },
	{ label: "Noruega", value: "norwegian" },
	{ label: "Finlandesa", value: "finnish" },
	{ label: "Danesa", value: "danish" },
	{ label: "Belga", value: "belgian" },
	{ label: "Holandesa", value: "dutch" },
	{ label: "Rusa", value: "russian" },
	{ label: "Rumana", value: "romanian" },
	{ label: "Cervecería", value: "brewery" },
	{ label: "Vinos y Tapas", value: "wine-and-tapas" },
	{ label: "Orgánica", value: "organic" },
	{ label: "Del Medio Oriente", value: "middle-eastern" },
	{ label: "Africana", value: "african" },
	{ label: "Australiana", value: "australian" },
	{ label: "Nórdica", value: "nordic" },
	{ label: "Del Pacífico", value: "pacific" },
	{ label: "Costa Oeste", value: "west-coast" },
	{ label: "Suroeste", value: "southwest" },
	{ label: "Costa Este", value: "east-coast" },
	{ label: "Medio Oeste", value: "midwest" },
	{ label: "Nueva Inglaterra", value: "new-england" },
	{ label: "Sur de Estados Unidos", value: "southern-us" },
];
